# Generated by Django 3.1.5 on 2021-02-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('group', models.CharField(choices=[('laptop', 'Laptop'), ('acc', 'Accessory'), ('pc', 'PersonalComputer'), ('phone', 'Phone')], default='phone', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
