# Generated by Django 3.1.5 on 2021-02-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('phone', 'Phone'), ('pc', 'PersonalComputer'), ('acc', 'Accessory'), ('laptop', 'Laptop')], default='phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='no_image.jpg', null=True, upload_to='product_image'),
        ),
    ]
