# Generated by Django 3.1.5 on 2021-02-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210224_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('pc', 'PersonalComputer'), ('phone', 'Phone'), ('laptop', 'Laptop'), ('acc', 'Accessory')], default='phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='product_image'),
        ),
    ]
